name: cv-learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - pyyaml
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - torch
      - torchvision
      - opencv-python
      - seaborn
      - tensorboard
